// This file is generated by Slice Machine. Update with care!

import Image from './Image'
import Quote from './Quote'
import Text from './Text'
import ContactForm from './ContactForm'

export {
	Image,
	Quote,
	Text,
	ContactForm
}

export const components = {
	image: Image,
	quote: Quote,
	text: Text,
	contact_form: ContactForm,
}
